// VoiceGallery.jsx — two zones:
//   • Archetypes — a browsable library of *designed* voices (no real people),
//     generated by VoiceStudio's own voice-design engine. Featured cards up top,
//     facet filters to explore hundreds. (core.archetypes / /archetypes API)
//   • My Imports — a neutral importer: paste any URL you have the rights to, or
//     upload a file, trim it, save it. The project ships no celebrity catalog.
import React, { useState, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { Sparkles, Store, Upload } from 'lucide-react';
import { Segmented } from '../ui';
import { archetypePreviewUrl, useArchetypeAsProfile } from '../api/archetypes';
import { previewVoiceUrl } from '../api/gallery';
import { useAppStore } from '../store';
import { apiUrl } from '../api/client';
import { playBlobAudio } from '../utils/media';
import { stopActivePlayback } from '../utils/playback';
import ArchetypesZone from '../components/gallery/ArchetypesZone';
import CommunityZone from '../components/gallery/CommunityZone';
import ImportsZone from '../components/gallery/ImportsZone';

export default function VoiceGallery() {
  const { t } = useTranslation();

  const zone = useAppStore((s) => s.galleryZone);
  const setZone = useAppStore((s) => s.setGalleryZone);
  const filters = useAppStore((s) => s.archetypeFilters);
  const setFilter = useAppStore((s) => s.setArchetypeFilter);
  const resetFilters = useAppStore((s) => s.resetArchetypeFilters);
  const favorites = useAppStore((s) => s.favoriteArchetypeIds);
  const toggleFavorite = useAppStore((s) => s.toggleFavoriteArchetype);
  const viewMode = useAppStore((s) => s.galleryViewMode);
  const setViewMode = useAppStore((s) => s.setGalleryViewMode);
  const setMode = useAppStore((s) => s.setMode);
  const setDefineMethod = useAppStore((s) => s.setDefineMethod);
  const setPendingProfileId = useAppStore((s) => s.setPendingProfileId);
  const setInstruct = useAppStore((s) => s.setInstruct);
  const setVdStates = useAppStore((s) => s.setVdStates);
  const vdStates = useAppStore((s) => s.vdStates);

  const [playingId, setPlayingId] = useState(null);
  const [loadingPreviewId, setLoadingPreviewId] = useState(null);
  const [notice, setNotice] = useState(null);
  const noticeTimer = useRef(null);

  const flash = (msg) => {
    setNotice(msg);
    if (noticeTimer.current) window.clearTimeout(noticeTimer.current);
    noticeTimer.current = window.setTimeout(() => setNotice(null), 3500);
  };

  // Fetch a preview clip and play it through the shared playback path
  // (playBlobAudio handles the Tauri "blob: URLs are dead in media elements"
  // detour — this page used to carry its own copy of that logic). The claim
  // routes to the global mini-player with the voice name as its label, and
  // starting any other playback stops this one (#316).
  const playUrl = async (fullUrl, id, label) => {
    if (playingId === id) {
      stopActivePlayback(); // onDone('stopped') below resets playingId
      return;
    }
    setLoadingPreviewId(id);
    try {
      // no-store: preview audio is re-rendered server-side when an archetype is
      // fixed/changed, but the URL is stable. Without this the WebView's HTTP
      // cache replays the first clip it ever fetched (a stale render) forever.
      const resp = await fetch(fullUrl, { cache: 'no-store' });
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
      const blob = await resp.blob();
      setPlayingId(id);
      await playBlobAudio(blob, {
        label,
        // ended / stopped / error all mean "this card is no longer playing".
        onDone: () => setPlayingId((cur) => (cur === id ? null : cur)),
      });
    } catch (e) {
      setPlayingId((cur) => (cur === id ? null : cur));
      flash(
        t('gallery.preview_failed', {
          message: e?.message || String(e),
          defaultValue: 'Preview unavailable: {{message}}',
        }),
      );
    } finally {
      setLoadingPreviewId(null);
    }
  };

  const zoneItems = [
    {
      value: 'archetypes',
      label: (
        <span className="inline-flex items-center gap-[5px]">
          <Sparkles size={14} /> {t('gallery.zone_archetypes', { defaultValue: 'Archetypes' })}
        </span>
      ),
    },
    {
      value: 'community',
      label: (
        <span className="inline-flex items-center gap-[5px]">
          <Store size={14} /> {t('gallery.zone_community', { defaultValue: 'Community' })}
        </span>
      ),
    },
    {
      value: 'imports',
      label: (
        <span className="inline-flex items-center gap-[5px]">
          <Upload size={14} /> {t('gallery.zone_imports', { defaultValue: 'My Imports' })}
        </span>
      ),
    },
  ];

  return (
    <div className="flex flex-col gap-[12px] p-[12px] h-full overflow-hidden">
      <div className="shrink-0">
        <div className="flex justify-between items-center">
          <div>
            <h2 className="text-[1.1rem] font-semibold m-0 text-[var(--text-primary)]">
              {t('gallery.title', { defaultValue: 'VoiceStudio Gallery' })}
            </h2>
            <p className="mt-[2px] mr-0 mb-0 ml-0 text-[0.72rem] text-[var(--text-secondary)]">
              {t('gallery.subtitle', {
                defaultValue: 'Hundreds of ready-made designed voices — pick one and go.',
              })}
            </p>
          </div>
          <Segmented items={zoneItems} value={zone} onChange={setZone} />
        </div>
      </div>

      {notice && (
        <div className="shrink-0 px-[10px] py-[7px] bg-bg-elev-2 border-l-[3px] border-l-[color:var(--accent)] rounded-[6px] text-[0.75rem] text-[var(--text-primary)]">
          {notice}
        </div>
      )}

      {zone === 'archetypes' ? (
        <ArchetypesZone
          t={t}
          filters={filters}
          setFilter={setFilter}
          resetFilters={resetFilters}
          favorites={favorites}
          toggleFavorite={toggleFavorite}
          viewMode={viewMode}
          setViewMode={setViewMode}
          playingId={playingId}
          loadingPreviewId={loadingPreviewId}
          onPreview={(a) => playUrl(archetypePreviewUrl(a.id), a.id, a.name)}
          onUse={async (a) => {
            try {
              // eslint-disable-next-line react-hooks/rules-of-hooks -- useArchetypeAsProfile is an API call, not a React hook
              const r = await useArchetypeAsProfile(a.id, a.name);
              // Hand the new profile to the synthesis view and jump there so the
              // user lands ready-to-generate instead of hunting for it in the list.
              setPendingProfileId(r.profile_id);
              setMode('studio');
              setDefineMethod('audio');
            } catch (e) {
              flash(
                t('gallery.use_failed', {
                  message: e?.message || String(e),
                  defaultValue: 'Could not create that voice: {{message}}',
                }),
              );
            }
          }}
          onDesign={(a) => {
            setVdStates({ ...vdStates, ...a.attrs });
            setInstruct('');
            setMode('studio');
            setDefineMethod('design');
          }}
        />
      ) : zone === 'community' ? (
        <CommunityZone
          t={t}
          playingId={playingId}
          loadingPreviewId={loadingPreviewId}
          favorites={favorites}
          toggleFavorite={toggleFavorite}
          onPlayAudio={(url, id, name) => playUrl(url, id, name)}
          flash={flash}
          onDesign={(instruct) => {
            setVdStates({ ...vdStates });
            setInstruct(instruct);
            setMode('studio');
            setDefineMethod('design');
          }}
        />
      ) : (
        <ImportsZone
          t={t}
          playingId={playingId}
          loadingPreviewId={loadingPreviewId}
          onPlayGallery={(v) => playUrl(apiUrl(previewVoiceUrl(v.id)), v.id, v.name)}
          flash={flash}
        />
      )}
    </div>
  );
}
