"""
Watermark detection API — upload audio, check if it was generated by VoiceStudio.
"""
import os
import tempfile
import logging
import torchaudio
from fastapi import APIRouter, UploadFile, File, HTTPException

from services.watermark import detect_watermark, is_enabled, _check_available
from core.prefs import get as pref_get, set_ as pref_set

logger = logging.getLogger("omnivoice.watermark_api")

router = APIRouter()


@router.post("/watermark/detect")
async def detect_audio_watermark(file: UploadFile = File(...)):
    """
    Upload an audio file and check whether it contains a VoiceStudio watermark.

    Returns confidence score, decoded message, and source attribution.
    """
    if not _check_available():
        raise HTTPException(
            status_code=503,
            detail="AudioSeal is not installed. Run `uv pip install audioseal` to enable watermark detection.",
        )

    # Accept common audio formats
    allowed = {".wav", ".mp3", ".flac", ".ogg", ".m4a", ".aac", ".opus"}
    ext = os.path.splitext(file.filename or "upload.wav")[1].lower()
    if ext not in allowed:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported format '{ext}'. Upload one of: {', '.join(sorted(allowed))}",
        )

    # Write to temp file for torchaudio to load
    try:
        with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
            content = await file.read()
            tmp.write(content)
            tmp_path = tmp.name

        waveform, sr = torchaudio.load(tmp_path)
        result = detect_watermark(waveform, sr)
        return result

    except Exception as e:
        logger.exception("Watermark detection failed")
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        try:
            os.unlink(tmp_path)
        except (OSError, UnboundLocalError):
            pass


@router.get("/watermark/status")
def watermark_status():
    """Return current watermark configuration."""
    return {
        "invisible_enabled": is_enabled(),
        "visible_audio_enabled": pref_get("watermark.visible_audio", False),
        "visible_video_enabled": pref_get("watermark.visible_video", True),
        "audioseal_available": _check_available(),
    }


@router.post("/watermark/settings")
def update_watermark_settings(
    invisible: bool | None = None,
    visible_audio: bool | None = None,
    visible_video: bool | None = None,
):
    """Update watermark preferences."""
    if invisible is not None:
        pref_set("watermark.invisible", invisible)
    if visible_audio is not None:
        pref_set("watermark.visible_audio", visible_audio)
    if visible_video is not None:
        pref_set("watermark.visible_video", visible_video)

    return {
        "invisible_enabled": pref_get("watermark.invisible", True),
        "visible_audio_enabled": pref_get("watermark.visible_audio", False),
        "visible_video_enabled": pref_get("watermark.visible_video", True),
    }
